application: scenic-rampart-127518
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
  
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: imdb/static
  
- url: /.*
  script: main.application
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'imdb.settings'